webtalk_init -webtalk_dir C:/PSUProj/ece361f18/pep9Verilog/sim/pep9Verilog/pep9Verilog.sim/sim_1/behav/xsim/xsim.dir/testbench_Pep9_CPU_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug 23 15:41:43 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2117270" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "177040059_1777489594_210648846_443" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8cd31dfc-2d27-4aea-abdf-b4070b3716c9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a3af9bf5e804434a863246e8b66d9eaf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "3" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "153 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "8 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "66" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "9" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.91_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "55800_KB" -context "xsim\\usage"
webtalk_transmit -clientid 605495761 -regid "177040059_1777489594_210648846_443" -xml C:/PSUProj/ece361f18/pep9Verilog/sim/pep9Verilog/pep9Verilog.sim/sim_1/behav/xsim/xsim.dir/testbench_Pep9_CPU_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/PSUProj/ece361f18/pep9Verilog/sim/pep9Verilog/pep9Verilog.sim/sim_1/behav/xsim/xsim.dir/testbench_Pep9_CPU_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/PSUProj/ece361f18/pep9Verilog/sim/pep9Verilog/pep9Verilog.sim/sim_1/behav/xsim/xsim.dir/testbench_Pep9_CPU_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
